### PR TITLE
destroy_unikernel: output the unix error when the kill failed

### LINKED ISSUE #235: Success: kill failed exit 2
A unikernel was stuck in a reboot loop, so I ran `albatross-client destroy nat0:opam-mirror` and got this funny message (likely it had halted before the kill command was executed).
```
host [unikernel: nat0:opam-mirror]: success: [unikernel: nat0:opam-mirror] kill failed exit 2
```

### PR DESCRIPTION
**Pull request by hannesm**
logs details, reports success, fixes #235

### CODE REVIEW

File: src/vmm_vmmd.ml [hunk 1]
```diff
@@ -420,7 +420,7 @@ let handle_unikernel_cmd t id =
         try
           Vmm_unix.destroy unikernel ; "destroyed unikernel"
         with
-          Unix.Unix_error _ -> "kill failed"
+          Unix.Unix_error (err, _, _) -> "kill failed " ^ Unix.error_message err
       in
       let s ex =
         let data = Fmt.str "%a %s %a" Name.pp id answer pp_process_exit ex in
```
Comment (hannesm) [inline src/vmm_vmmd.ml]:
```suggestion
        let data = "destroyed unikernel" in
```
